version: '2'
services:
  nginx:
    network_mode: host
    image: nginx:mainline
    restart: always
    volumes:
      - ./config:/etc/nginx/conf.d/:ro
      - ./ssl:/etc/nginx/ssl/:ro
      - /srv/www:/srv/www:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

